version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: financi
    ports:
      - "8765:5432"
    volumes:
      - "/var/lib/postgresql/data"
  
  server:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/financi
      PORT: 8080
      SECRET_KEY: dev
      SWAGGER_UI_HOST: localhost:8080
      COOKIE_DOMAIN: localhost
      ENVIRONMENT: debug