name: CI workflow

on:
  push:
    branches:
      - dev

jobs:
  lint:
    name: Run Eslint
    uses: grupo-bala/.github/workflows/lint.workflow.yml
  
  test:
    name: Run tests
    uses: grupo-bala/.github/workflows/test.workflow.yml