name: Lint workflow

on:
  workflow_call

jobs:
  test:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Setup for lint
        uses: ./.github/workflows/setup.workflow.yml
      
      - name: Run eslint
        run: npm run lint