name: Test workflow

on:
  workflow_call

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup for tests
        uses: ./.github/workflows/setup.worflow.yml
      
      - name: Run tests
        run: npm test -- --collectCoverage
        env:
          SECRET_KEY: test
          PORT: 8080
          DATABASE_URL: none

      - name: Deploy coverage
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: coverage/lcov-report