name: Test workflow

on:
  push:
    branches:
      - dev

jobs:
  setup:
    name: Setup workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Use node
        uses: actions/setup-node@v3.5.1
        with:
          cache: 'npm'
      
      - name: Install dependencies
        run: npm i
  
  lint:
    name: Run Eslint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run eslint
        run: npm run lint
  
  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: npm test -- --collectCoverage
        env:
          SECRET_KEY: test
          PORT: 8080
          DATABASE_URL: none
  
  coverage:
    name: Deploy coverage
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Deploy coverage
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: coverage/lcov-report