name: Test workflow

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Use node
        uses: actions/setup-node@v3.5.1
        with:
          cache: 'npm'
      
      - name: Run tests
        run: npm i && npm test
        env: 
          SECRET_KEY: test